### PR TITLE
Add galata bot

### LINKED ISSUE #79: Add bot to update galata references
[jupyterlab/maintainer-tools/.github/actions/update-snapshots@main](https://github.com/jupyterlab/maintainer-tools/blob/main/.github/actions/update-snapshots/action.yml)

### PR DESCRIPTION
**Pull request by trungleduc**
Closes #79 
The command to update the snapshot is `please update snapshots`

### CODE REVIEW

**Comment by trungleduc** [comment]
Please update galata references

**Comment by trungleduc** [comment]
I tested the bot in my fork and It works.

**Comment by trungleduc** [comment]
I need to update the Ui test script.

**Review by hbcarlos — APPROVED** [review]
Thanks, @trungleduc!

**Pull request merged**
