### PR TITLE
Multi selection

### LINKED ISSUE #131: Support multi-selection
We should support multi-selection of 3D shapes.

This will then allow the following scenario:
- Select shape A
- Select shape B as well
- Press Union/Cut operator -> The form is already filled with shape A and shape B as parameters

### LINKED ISSUE #137: Pre-fill operator dialogs
We should pre-fill the dialog when creating a new operation with the current selection

### PR DESCRIPTION
**Pull request by martinRenou**
[Screencast from 2023-05-16 09-49-16.webm](https://github.com/QuantStack/jupytercad/assets/21197331/76921d09-af4f-40fc-bcbb-719d8be9fa96)

Fix #131 and fix #137

### CODE REVIEW

**Comment by martinRenou** [comment]
The UI-tests are polluted by the JupyterLab 4 update notification

**Comment by trungleduc** [comment]
> The UI-tests are polluted by the JupyterLab 4 update notification

IIRC there is a config to disable the notification popup

**Comment by martinRenou** [comment]
Visual regression is legit now

**Comment by martinRenou** [comment]
Converting to draft, I want to add support for multi-selection in the tree view and add a visual regression test for it.

**Comment by martinRenou** [comment]
please update snapshots again

**Comment by martinRenou** [comment]
The PR also fixes an issue with selection bouncing between the tree and the 3d view

**Comment by martinRenou** [comment]
please update snapshots again

**Comment by martinRenou** [comment]
@trungleduc green again

**Review by trungleduc — APPROVED** [review]

**Comment by trungleduc** [comment]
Thanks @martinRenou

**Pull request merged**
