### PR TITLE
Toolbar refactor and styling

### LINKED ISSUE #49: The "PART" dropdown does support clicking on the "caret" icon
Screenshot from 2022-12-05 11-59-46

### LINKED ISSUE #125: Improve UI toolbar
We should improve the toolbar and use some nice icons for primitives and operations:

Screenshot from 2023-04-24 16-24-39

Screenshot from 2023-04-24 16-25-07

### PR DESCRIPTION
**Pull request by martinRenou**
Would fix #125 and fix #49

- Turn toolbar buttons into JupyterLab commands
- Move commands logic in its own file
- Improve the UI and UX of the toolbar (no dropdown, new icons, less clicks)

Screenshot from 2023-05-05 12-53-14

### CODE REVIEW

**Comment by martinRenou** [comment]
Remaining TODO:
- [ ] Rebase and fix conflicts 😄 
- [ ] Refactor user toolbar
- [ ] Spacers in the toolbar

**Comment by martinRenou** [comment]
I probably need to update the integration tests and screenshots, but the rest is ready to review.

**Comment by martinRenou** [comment]
please update snapshots

**Review by trungleduc — APPROVED** [review]

**Comment by trungleduc** [comment]
Thanks @martinRenou

**Pull request merged**
