### PR TITLE
Fixes objects tree view

### LINKED ISSUE #48: Keep the tree unfolded when clicking on objects
When clicking on shapes in the tree we close other objects, we should not change the tree state when clicking on shapes

[Screencast from 2022-12-05 11-57-17.webm](https://user-images.githubusercontent.com/21197331/205620706-ab6b6a2e-6194-4b9b-94a8-a51d89e83d69.webm)

### PR DESCRIPTION
**Pull request by hbcarlos**
Fixes #48

### CODE REVIEW

**Comment by trungleduc** [comment]
Thanks a lot @hbcarlos, could you add a screenshot test for the tree component?

**Comment by hbcarlos** [comment]
This is a screencast of the new behavior.


https://user-images.githubusercontent.com/26092748/208941117-762f00e2-9735-45e2-9a84-93a58b81ef4a.mov

**Comment by trungleduc** [comment]
Great! Can I push on your branch for the tree UI test?

**Comment by hbcarlos** [comment]
Sure. Feel free to push.

**Review by trungleduc — APPROVED** [review]

**Comment by trungleduc** [comment]
Thanks @hbcarlos !

**Pull request merged**
