### PR TITLE
Allow changing camera settings

### PR DESCRIPTION
**Pull request by martinRenou**
Add Camera settings 

For now we can only change the projection, but we could later change the FOV etc

Screenshot from 2023-06-29 10-36-52
Screenshot from 2023-06-29 10-36-25

### CODE REVIEW

**Review by trungleduc — APPROVED** [review]

**Comment by trungleduc** [comment]
Thanks @martinRenou

**Comment by trungleduc** [comment]
We may need to fix https://github.com/QuantStack/jupytercad/issues/203 to be able to release

**Comment by martinRenou** [comment]
Let's see if that fixes it https://github.com/QuantStack/jupytercad/pull/205

**Comment by martinRenou** [comment]
please update snapshots

**Pull request merged**
